# Site
title: matt schaar
description: a personal collection of writings and hodgepodge
#url: http://moby.github.io
logo: logo.png                                       # Site logo
locale: en_US

# Left Block Images
background:
  homepage: images/picove.jpg                           # this image will be shown on homepage's left block
  post-list: images/tdp.JPG            # this image will be shown on post list page
  default-post: images/hawkhill.jpg   # this image will be shown when post's front matter doesn't specify any image

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Google Analytics
google-analytics: UA-88064661-1

# Social Links
#email:             email
#google.plus:        username
twitter:            mattschaar
#facebook:           username
github:             schaar
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:          mattschaar
#xing:              username
instagram:          _schaar_
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#behance:           username
medium:             mattschaar

# Gems
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]
